### ISSUE TITLE
RxJS version 5 update

### ISSUE THREAD

**Issue by anodynos** [njl07/rx-http-request#1]
First of all congrats for this lib - its something that is really needed for modern multiplatform development. BTW, it hasn't got many stars/adoption, I guess it needs some tweeting, blogging mentions etc

To the question, any plans for an `rxjs@5` update ?

**Comment by njl07** [comment]
Thanks for your interest.

I'll update ASAP to new `rxjs` version.

I would like to have more stars and users and I have tweeted for this library.

If you know how to share more you are welcome and if you want to contribute you are too.

**Comment by njl07** [comment]
@anodynos update was performed and sorry for the delay but I was so busy.

What do you mean about implements `Subject` to have event stream in `GET` methods and all process can subscribe to these and be notified on request is performed?

**Comment by anodynos** [comment]
Hey Nicolas, thanks! I will surely tweet it, but it needs more traction - make sure you let the rxjs authors know about it and the request authors/users also.

PS: I don't understand your `implements Subject` question at all - sorry!
