### ISSUE TITLE
Allow for Constructor config of underlying Request

### ISSUE THREAD

**Issue by RavenHursT** [njl07/rx-http-request#14]
One can use `Request`'s constructor directly to kick of an http request, without using the convenience methods (`.post`, `.put`, etc): https://github.com/request/request#examples

I tried doing the same w/ RxHR: 
```
import {RxHR} from '@akanass/rx-http-request'

RxHR({
  method: 'POST',
  uri: 'http://localhost:3000/api',
  etc,
  etc
})...
```

I ended up getting `RxHR is not a function`.

It would be nice to have the interface for `RxHR` be the same here as `Request`.

**Comment by njl07** [comment]
Hello @RavenHursT ,

I need to check for this one because we change the initial interface calls to add `Observable` and I don't know if can do this one.
