### ISSUE TITLE
Make module "universal"

### ISSUE THREAD

**Issue by RavenHursT** [njl07/rx-http-request#15]
Right now, in order to use this library in a "universal" or "isomorphic" app, one must either utilize dynamic require statements to import the `/browser` package for client-side bundling, or else, configure Webpack (or whatever bundling tool) to alias `@akanass/rx-http-request` to `@akanass/rx-http-request/browser` for the client.

I did the latter:

```
// webpack.config.js
{
  resolve: {
    alias: {
      '@akanass/rx-http-request': '@akanass/rx-http-request/browser'
    }
  }
}
```

Seems to be working, but would be nice if this just worked "out of the box" like this package: https://github.com/mcmunder/universal-rxjs-ajax

**Comment by njl07** [comment]
Hello @RavenHursT,

I'll do it ASAP like ask in PR #13

**Comment by njl07** [comment]
@RavenHursT can you try to install new version from next `@akanass/rx-http-request@next` and tell me if it's working?

You must have `v2.7.0-rc.0`

**Comment by njl07** [comment]
@RavenHursT I've just published a new version of the library includes 3 bundles `commonjs`, `es5` and `es2015`.

The `main` version is `commonjs` but in `module` section, we've `es5` version and normally, `webpack`must find it and works fine.

Can you install the `next` version with `@akanass/rx-http-request@next` and you'll have `v2.7.0-rc.1`.

Delete your alias and test it.

Thanks for your feedback.

**Comment by RavenHursT** [comment]
Awesome.. I'll give it a shot in a bit...

**Comment by njl07** [comment]
All works fine in #12 so you can follow the discussion if you have a problem but normally all will be fine and I’ll publish the release tomorrow morning

**Comment by njl07** [comment]
I've just tested with a `webpack` application of my collaborateur and all works fine.

You must add a node section inside your config :
```javascript
node: {
  fs: "empty",
  tls: "empty",
  net: "empty"
}
```

I try to solve issue #14 before publish new release but if you want test you can install `v2.7.0-rc.1`

**Comment by njl07** [comment]
`v2.7.0` published

**Comment by RavenHursT** [comment]
This is working now.. finally got around to "testing" it.. once I finally hit a brick wall in trying to debug something related.. ugh..

https://stackoverflow.com/a/48939709/282250
