### ISSUE TITLE
RxHR should be "default" export of package

### ISSUE THREAD

**Issue by RavenHursT** [njl07/rx-http-request#16]
Is there a reason why `.RxHR` isn't he `default` export for this package?

If it were, then one would just have to do:
`import RxHR from '@akanass/rx-http-request'`

rather than...

`import { RxHR } from '@akanass/rx-http-request'`

**Comment by njl07** [comment]
Because if you do `default` export and use `commonjs` require, you must do : 
`require('@akanass/rx-http-request').default`

So not good to use like this.
