### ISSUE TITLE
Shouldn't RxJS be a runtime dependency?

### ISSUE THREAD

**Issue by RavenHursT** [njl07/rx-http-request#17]
`rxjs` is listed as a `devDependency` in the `package.json`, but it's here in runtime code: https://github.com/njl07/rx-http-request/blob/master/src/lib/RxHttpRequest.ts#L11

**Comment by njl07** [comment]
`RxJS` is declared as `devDependecies` and `peerDependencies` so you must install `rxjs` with this package like it’s explain in readme
