### ISSUE TITLE
Typo in README.md browser example

### ISSUE THREAD

**Issue by RavenHursT** [njl07/rx-http-request#18]
The example has the object as `rhr.RxHR`, but it's actually `rhr.RxHttpRequest`:

https://jsbin.com/merizax/edit?html,js,console

**Comment by njl07** [comment]
Browser version works like it’s explain in readme and all works fine

**Comment by RavenHursT** [comment]
@njl07 Did you look at the jsbin I included?

https://jsbin.com/merizax/edit?html,js,console

I've changed it now to reflect the README.md and it quite clearly fails to work because `rhr.RxHR` is `undefined`.

<img width="540" alt="screen shot 2017-11-14 at 12 24 44 pm" src="https://user-images.githubusercontent.com/496983/32802971-d6a334d6-c936-11e7-9f91-76712e0f8078.png">

**Comment by njl07** [comment]
Just check the version of you deploy on your example and of my `package.json` and so on `npm` and you will find why I said all it’s ok for me

**Comment by RavenHursT** [comment]
Ahhh.. now I see where the confusion lies.. any idea why NPM reports the version to be `1.2.0`?

https://www.npmjs.com/package/rx-http-request

**Comment by RavenHursT** [comment]
Ah... now I get it.. https://www.npmjs.com/package/@akanass/rx-http-request is the current project..

The @akanass keeps throwing me off..
