### ISSUE TITLE
Use splats 

### ISSUE THREAD

**Issue by anodynos** [njl07/rx-http-request#2]
You can use splats (copied from http://coffeescript.org/) in ES6 - so 

```
var myFun = function (
// create new args array
	const args = new Array(arguments.length);

	// inserts arguments inside
	Object.keys(arguments).forEach((key, index) => args[index] = arguments[key]);
}
```

simply becomes 

```
var myFun = function (...args) {}
```
and no comments are needed :-)

**Comment by njl07** [comment]
Yes, I can use `spread` operator but when I wrote this library, `NodeJS` didn't allowed this feature.

I must check if it's OK now.

**Comment by anodynos** [comment]
Oh, you're not `babelify`-ing it :-/  
I thought you were (this should be another issue:)

**Comment by njl07** [comment]
Done
