### ISSUE TITLE
Odd compiler errors with stenciljs

### ISSUE THREAD

**Issue by gdjennings** [njl07/rx-http-request#22]
Not sure where the source of the problem is but importing the browser package in stenciljs can't find module intermittently.

```
Cannot find module '@akanass/rx-http-request/browser'.

      L2:  import moment from 'moment';
      L3:  import http from '@akanass/rx-http-request/browser';
```
see
ionic-team/stencil#340

**Comment by njl07** [comment]
@gdjennings you can't use `browser` version in an `import` because it's a standalone version like explain in the `README`.

You just need to `import` library :
```typescript
import { RxHR } from '@akanass/rx-http-request';
```

And your compiler like `webpack`, `tsc`, `node` ... will find the good module version.
