### ISSUE TITLE
RxHttpRequest.request is not a function

### ISSUE THREAD

**Issue by ryan-strandt** [njl07/rx-http-request#23]
documentation looks like there is a request function on RxHttpRequest but I don't see it in the src. Is there a way that we can change the mode of a request made?

Essentially I am trying to get around an issue where third party api does not have an Access-Control-Allow-Origin header in the response headers therefore I am getting 
```
No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost' is therefore not allowed access. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```
Any thoughts?

**Comment by njl07** [comment]
Yes isn’t because it’s `RxHR.request`

And for security reason I don’t understand why you want to access API in your `browser` without `CORS`.

If API doesn’t provide `CORS` headers it’s maybe they don’t want you access to it by a `browser`

**Comment by ryan-strandt** [comment]
Was using old api docs - sorry.
