### ISSUE TITLE
RxHR request post appends body params to the URI

### ISSUE THREAD

**Issue by kaliaparijat-prosper** [njl07/rx-http-request#24]
I am not certain if I am doing this correct, but I want to perform a POST operation to a JSON API, so I do this:

```
 const options = {
      headers: req['httpHeaders'],
      body: req['body'], // This is in JSON, coming in from a browser network HTTP POST call as well
      json: true,
    };
    const url = `http://someURI/accounts`;
    RxHR.post(url, options).subscribe((resp) => {
      const params = {
        res: res,
        responseData: resp
      };

```
And what this does is, it appends the POST params to the URI in addition to doing a normal POST call. Basically: 
`http://someURI/81/accounts?{{req['body']}}`

Kind of bizzarre, right? It should simply perform the POST operation without appending this to the URI. The end result is that my API returns a 301 response code to me.
Is this by design of rx-http-request or is my API incorrect to return a 301 response or am I mixing things up

**Comment by njl07** [comment]
I think the problem is the data passed inside `body` field in `options`

Did you tried with a `static JSON` in `body`? And good headers object in `headers` field?

I never had problem with my library and all people use it too.

**Comment by kaliaparijat-prosper** [comment]
@njl07 : have used this library to perform PUT, GET operations in the same app with the same set of headers, so that rules out the headers object. I can try with static JSON, but I am curious why it would simply append the JSON to the URI as a parameter when performing a POST operation

**Comment by njl07** [comment]
I don’t know why because I’ve not the problem.

That’s why test with static `JSON` to check if it works or not.
