### ISSUE TITLE
Support for Generics for responses?

### ISSUE THREAD

**Issue by kylecannon** [njl07/rx-http-request#28]
Hi, is there any plans for supporting generics for responses?

**Comment by kylecannon** [comment]
Right now when you do a request EX: `request.get('/foo').pipe(map(r => r.body))`, body is of type `any`. If we were able to add generics for the get request EX: `request.get<MyFooInterface>('/foo')`

See  how angular does it with their http library: https://angular.io/guide/http#making-a-post-request

**Comment by kylecannon** [comment]
By the way, forgot to say thank you for the awesome library :+1:

**Comment by njl07** [comment]
I understood I can add it with the migration on `RxJS` V6

**Comment by kylecannon** [comment]
That would be fantastic. Thank you very much. This would greatly increase the workarounds I am doing right now for typings.

**Comment by njl07** [comment]
`v3.0.0` published with `generics` and `rxjs v6+`
