### ISSUE TITLE
`request` library does not support HTTP request canceling 

### ISSUE THREAD

**Issue by anodynos** [njl07/rx-http-request#3]
I am not sure this is the right place, but just for discussion, I think one the strongest points of Rx is the resource management and the automatic cleaning up / cancelation / unsubscription it does. 

But this only if the underlying API supports it - `request` doesn't. 

But [XMLHttpRequest does](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/abort) and its a quite a useful feature, especially for the browser.

**Comment by njl07** [comment]
Like my question on a previous comment, I think we must implements `Subject` feature of `RxJS`.

How do you mean for this?

**Comment by anodynos** [comment]
I don't think `Subject` has anything to do with it or will solve any problems - we dont want to emit our own http results on the stream. 

You need to look into `ro.abort` - but maybe there are issues with it - check :

https://github.com/request/request/issues/2025
https://github.com/request/request/issues/2255
https://github.com/request/request/pull/2052
