### ISSUE TITLE
Not able to post zip file as multipart/form-data to Spring server 

### ISSUE THREAD

**Issue by gianmarcogiummarra** [njl07/rx-http-request#34]
Hello,
I am trying to perform a post request with a zip file as multipart/form-data.
I've been trying with different headers

`const formData = new FormData();
    formData.append("name", fileName);
    formData.append("filedata", fs.createReadStream("path/to/my/file.zip")
  );

  return baseRequest.post("server/upload", {
    body: formData,
    headers: {
      "Content-Type": "multipart/form-data;",
    },
  });`

If I don't set the content-type header, from my spring server (Geoserver) I get "415 - Unsupported Media Type", while setting it as in the above snippet, I get "500 - server error".

I tried to upload the same file through an angular application, using the classic Angular's HttpClient library, and it works on the same server.

This is the working code for Angular:
`const formData = new FormData();
    formData.append("name", file.name);
    formData.append("filedata", file);

    return this.http.post(
      "server/upload",
      formData,
      {
        headers: {
          Authorization: "<auth>",
        },
      }
    );`

P.S.: Authorization header in the first snippet is contained in baseRequest.

Since I didn't manage to find any documentation for form-data during post for this package, is there anything I'm doing wrong or there's some limitation I'm not taking into account?

**Comment by akanass** [comment]
hi @gianmarcogiummarra the header is for sure required and the error has to be check inside your server.

But what I can see in your code is you're using `body` instead of `formadata` inside the `POST` method like explain in the official `request` library https://github.com/request/request#multipartform-data-multipart-form-uploads

**Comment by gianmarcogiummarra** [comment]
Hello @akanass, you saved my day. Thank you!
Didn't think about checking the request package docs.
